platform :ios, '10.0'

target 'InkChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IBAnimatable', '~> 4.1.0'
  pod 'Alamofire', '~> 4.4.0'

  # Pods for InkChat

  target 'InkChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InkChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
